# Generated by Django 5.2.3 on 2025-07-06 20:03

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_content2_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content3',
            field=mdeditor.fields.MDTextField(null=True, verbose_name='md2內容'),
        ),
    ]
